_BASE_: "cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "model_0039999_e76410.pkl"
  ROI_HEADS:
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (140000, 180000)
  MAX_ITER: 200000
  BASE_LR: 0.02
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 0
DATASETS:
  TRAIN: ("CIHP_train")
  TEST: ("CIHP_val",)
OUTPUT_DIR: "./finetune_output"

